import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <header className="text-orange-600 font-semibold font-sans text-base body-font bg-black">
  <div className="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
   <Image className="ml-24" src={"/logo4.png" }
   alt="logo"
   width={120}
   height={120}/>
    <nav className="md:ml-auto flex flex-wrap items-center text-base justify-center gap-10">
      <Link className="mr-5 hover:text-white" href={"/"}>Home</Link>
      <Link className="mr-5 hover:text-white" href={"/about"}>About</Link>
      <Link className="mr-5 hover:text-white" href={"#"}>Blog</Link>
      <Link className="mr-5 hover:text-white" href={"/contact"}>Contact</Link>
    </nav>
   
  </div>
</header>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
